#!/bin/sh
#PBS -M arun@temple.edu
#PBS -l walltime=48:00:00
#PBS -l nodes=1:ppn=1
#PBS -N astral
#PBS -q big
#PBS
cd $PBS_O_WORKDIR

export PATH=$PATH:/home/tuf29140/work/DcoccGenome/standard-RAxML/
module load java

#astralinput.tre is the input containing all the RAXML gene trees
#astraloutput.tre is the consensus species tree that is generated by ASTRAL

java -jar astral.5.7.5.jar -i Phylogeny/astralinput.tre -o astraloutput.tre > astralout_1.log	
